const cards = [
  {
    id: 1,
    worth: 999,
    title: "New Macbook Air",
    description: "Apple's latest macbook air in space gray",
    time: 5,
    ticketsPerEntry: 2,
    drawType: "Live",
    price: 5.0,
    image: "macbook.png",
  },
  {
    id: 2,
    worth: 510,
    title: "Win a PlayStation 5",
    description:
      "Marvel at incredible graphics and experience new PS5 features. ",
    time: 5,
    ticketsPerEntry: 1,
    drawType: "Instant",
    price: 1.11,
    image: "ps5.png",
  },
  {
    id: 3,
    worth: 921,
    title: "iPhone 12 Pro Max",
    description: "Apple's latest macbook air in space gray",
    time: 5,
    ticketsPerEntry: 1,
    drawType: "Instant",
    price: 3.25,
    image: "iphone.png",
  },
  {
    id: 4,
    worth: 7150,
    title: "LG OLED77GX6LA 4K SMAART TV",
    description: "The most innovative technology in TV",
    time: 5,
    ticketsPerEntry: 1,
    drawType: "Live",
    price: 6.52,
    image: "lgtv.png",
  },
  {
    id: 5,
    worth: 251,
    title: "Apple Watch Series 3",
    description:
      "Featuring Streaming Music, Faster Dual-Core Processor and watchOS 4",
    time: 5,
    ticketsPerEntry: 2,
    drawType: "Instant",
    price: 3.75,
    image: "appleWatch.png",
  },
  {
    id: 6,
    worth: 541,
    title: "Rolex GMT Master II",
    description: "They are watches that invite you on an adventure",
    time: 5,
    ticketsPerEntry: 1,
    drawType: "Live",
    price: 7.55,
    image: "rolex.png",
  },
  {
    id: 7,
    worth: 52121,
    title: "Jaguar XJ Ultimate ",
    description:
      "New Jaguar XJ Ultimate offers supercar speed and unrivalled opulence",
    time: 5,
    ticketsPerEntry: 2,
    drawType: "Instant",
    price: 50.75,
    image: "jaguar.png",
  },
  {
    id: 8,
    worth: 50000,
    title: "£50,000 Cash Injection",
    description: "Treat yourself now lockdown's lifting!",
    time: 5,
    ticketsPerEntry: 2,
    drawType: "Instant",
    price: 3.75,
    image: "cashInjection.png",
  },
];
export default cards;
